### ISSUE TITLE
Rename to canonical-sphinx-extensions

### ISSUE THREAD

**Issue by ru-fu** [canonical/canonical-sphinx-extensions#25]
This extension package is used not only in the LXD documentation, so the name is misleading.

**Comment by pmatulis** [comment]
We do not use 'canonical' in our other Canonical repository names (i.e. not canonical-sphinx-docs-guide') so I vote for 'sphinx-extensions' or 'sphinx-docs-extensions'.

**Comment by ru-fu** [comment]
> We do not use 'canonical' in our other Canonical repository names (i.e. not canonical-sphinx-docs-guide') so I vote for 'sphinx-extensions' or 'sphinx-docs-extensions'.

That's fine for the repo name - but the extension package is served through PyPI, so we need something unique there. While `sphinx-extensions` might be available, I don't think it's a good name for a generally available package.

**Comment by pmatulis** [comment]
I see. So what about contributing this to an upstream package?

**Comment by ru-fu** [comment]
There is no upstream package - if there was, we would be using it. ;)
Basically, everyone who needs an extension creates one. I haven't been able to find any extensions that address the specific things we needed (first for LXD, now in general for all our docs), that's why I collected new extensions that provide the needed functionality in this repo/package.

What we could do in theory is split them up into one package per extension and use the extension names as package names, but that would multiply the effort to support them. So I think just having one package with all the stuff we recommend for Canonical docs makes most sense.

**Comment by pmatulis** [comment]
What I meant was, are there not upstream packages out there that include multiple extensions?

**Comment by pmatulis** [comment]
I understand better now. Naming however a generally available package after a private company is bad form in my opinion. Is there any precedent for that? It would be better to name it 'rufus-sphinx-extensions'. :+1: :+1:

**Comment by ru-fu** [comment]
Hmm, I see your point, but I have no useful other suggestions. :( It's not "my" extensions, it's the ones that we need for Canonical documentation.

I discussed with @evildmp now, and he suggested `canonical-sphinx-extensions` as well, so let's go for that.
