### ISSUE TITLE
Project has no changelog/release notes/etc

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/canonical-sphinx-extensions#42]
It would be useful to know what's changed between releases, but I can't find that anywhere - the releases on GitHub are outdated, there's no CHANGES or RELEASES file in the repo, I can't find anything in the README, etc.

If it's "every commit to main is a new release" so you're meant to just `git log`, then mentioning that somewhere would be great. If changes are bundled into releases, then it would be great if those were documented somewhere.

**Comment by ru-fu** [comment]
We're releasing from main, and mostly after every commit.
So yes, the Git log is the best source, maybe coupled with https://pypi.org/project/canonical-sphinx-extensions/#history
